### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/developer.bitcoin.com#182]
The following typos were reported:

Not sure where (channel) to share this.  Marc De Mesel has pointed out the following spelling errors or typos at developer.bitcoin[.]com/ and developer.bitcoin[.]com/learn

]developer.bitcoin[.]com/learn
Mastering Bitcoin Cash
Based on Mastering Bitcoin by Andreas M. Antonopoulos, Mastering Bitcoin Cash is the ultimate guide to -"the"- bring your knowledge from beginner to professional step by step.
//remove -"the"-

Tutorials
Step by step instructions to build Bitcoin Cash apps from scratch. See real world examples -"get"- built and have your own working copies to bootstrap your project from.
//remove -"get"-

developer.bitcoin[.]com/
Build the foundation of knowledge needed to create world changing apps. -"Get"- Tutorials, blog posts, video streams and code snippets to help you go from being a hobbyist to a professional step by step.
//add Get

**Comment by pzenger** [comment]
Great, I'll do a quick audit over the phrasing across the pages today.  
Some of the above suggested fixes are incorrect, will spend about 30-60 minutes doing this in the morning.

**Comment by pzenger** [comment]
Closing this issue as PR addressing them has been merged
