### ISSUE TITLE
Improve the Testnet

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/developer.bitcoin.com#53]
The testnet is one of the most undervalued assets in BCH. We have the opportunity to add huge value by improving it 

## testnet faucet for $BCH and $WHC

* https://github.com/Bitcoin-com/developer.bitcoin.com/issues/55

## tREST v2

All work on [REST v2](https://github.com/Bitcoin-com/rest.bitcoin.com/issues/48) will apply to tREST

## testnet explorer 

https://explorer.bitcoin.com/bch will support testnet w/ a coming revamp. 

## cli-wallet

* https://github.com/Bitcoin-com/developer.bitcoin.com/issues/54

**Comment by christroutner** [comment]
All the above goals have been accomplished. Closing.
