### ISSUE TITLE
cli-wallet

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/developer.bitcoin.com#54]
This is a prototype Bitcoin Cash (BCH) wallet that runs on the command line. This
project has the following goals:
- Create a code base for a wallet that is easily forkable and extensible by JavaScript developers.
- Code an HD wallet that follows [these privacy best practices](http://bitcoinism.blogspot.com/2013/07/reclaiming-financial-privacy-with-hd.html)
- Include an interface for a CoinJoin or [equivalent service described here](https://gist.github.com/christroutner/457b99b8033fdea5ae565687e6360323)

Leverage @christroutner's [existing work](https://github.com/christroutner/bch-cli-wallet)

**Comment by christroutner** [comment]
bch-cli-wallet has been moved to the Bitcoin-com repository.
