### ISSUE TITLE
testnet faucet for $BCH and $WHC

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/developer.bitcoin.com#55]
* Leverage @christroutner's [existing work](https://github.com/christroutner/testnet-faucet)
  * [Live example](https://faucets.christroutner.com/bch/)

We're going to be adding the front end of this to developer.bitcoin. We need 3 landing pages
  
* /faucets 
* /faucets/bch 
* /faucets/whc

Work has started in the /faucet branch https://github.com/Bitcoin-com/developer.bitcoin.com/tree/faucet

**Comment by christroutner** [comment]
All work in this issue was completed a month or two ago. Closing this issue.
